---
- hosts: all
  become: true
  vars:
    home_path: "/home/odroid"
    dotnet_path: "/home/odroid/installations"
    dotnet_installer_url: "https://dot.net/v1/dotnet-install.sh"
    dotnet_installer_version: "latest"
    dotnet_installer_channel: "7.0"

  tasks:
  - name: Create installations dir
    file:
      path: "{{ dotnet_path }}"
      state: directory

  - name: Download dotnet installer
    get_url:
      url: "{{ dotnet_installer_url }}"
      dest: "{{ dotnet_path }}"
      mode: "+x"

  - name: Execute the dotnet installer
    command: >
      {{ dotnet_path }}/dotnet-install.sh
      --version {{ dotnet_installer_version }}
      --channel {{ dotnet_installer_channel }}
    register: dotnet_installer_execution
    notify:
      - Move .dotnet dir, ignore on existence
      - Add dotnet to .bashrc

  handlers:
    - name: Move .dotnet dir, ignore on existence
      command: mv /root/.dotnet {{ home_path }}/.local/bin/
      when: dotnet_installer_execution.rc == 0
      ignore_errors: true

    - name: Add dotnet to .bashrc
      lineinfile:
        dest: "{{ home_path }}/.bashrc"
        line: |
          export DOTNET_ROOT={{ home_path }}/.local/bin/.dotnet
          export PATH=$DOTNET_ROOT:$PATH
        state: present
        create: false
